dist: bionic
language: cpp
before_script:
  - mkdir build
  - cd build

matrix:
  include:
  #
  # G++ 
  #
  - os: linux
    env:
      - TEST="G++ 6"
    script:
      - cmake -DCMAKE_CXX_COMPILER="g++" ..
      - make

  #
  # Clang 
  #
  - os: linux
    env:
      - TEST="Clang 3.8"
    script:
      - cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
      - make

  #
  # Codecov
  #
  - os: linux
    env:
      - TEST="Codecov"
    script:
      - cmake -DENABLE_COVERAGE=ON -DCMAKE_CXX_COMPILER="g++" ..
      - make
      - cd ..
      - bash <(curl -s https://codecov.io/bash)
 
