dist: bionic
language: cpp
before_script:
  - mkdir build
  - cd build

matrix:
  include:
  #
  # G++ 
  #
  - os: linux
    env:
      - TEST="G++"
    script:
      - cmake -DCMAKE_CXX_COMPILER="g++" ..
      - make
      - make test

  #
  # Clang 
  #
  - os: linux
    env:
      - TEST="Clang"
    script:
      - cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
      - make
      - make test

  #
  # Codecov
  #
  - os: linux
    env:
      - TEST="Codecov"
    script:
      - cmake -DENABLE_COVERAGE=ON -DCMAKE_CXX_COMPILER="g++" ..
      - make
      - make test
      - cd ..
      - bash <(curl -s https://codecov.io/bash)

  #
  # Google Address Sanitizer
  #
  - os: linux
    env:
      - TEST="Google Address Sanitizer"
    script:
      - cmake -DENABLE_ASAN=ON ..
      - make
      - make test

  #
  # Google Undefined Sanitizer
  #
  - os: linux
    env:
      - TEST="Google Undefined Behaviour Sanitizer"
    script:
      - cmake -DENABLE_USAN=ON ..
      - make
      - make test

  #
  # Google Thread Sanitizer
  #
  - os: linux
    env:
      - TEST="Google Thread Sanitizer"
    script:
      - cmake -DENABLE_TSAN=ON ..
      - make
      - make test
  #
  # Valgrind
  #
  - os: linux
    env:
      - TEST="Valgrind"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - valgrind
    script:
      - cmake ..
      - make
      - ctest -T memcheck
 
